run_name: "PG_prior_only"
modelname: "DoTA"
batch_size: 256

dotakwgs:
  use_fourier_embedding: True
  in_channels: 3

losskwgs:
  allMAE_weight: 1.
  masked_factor: 5.0
  iid_curve_weight: 0.001
  use_high_dose_mask: False
  bragg_peak_weight: 25.0


train:
  num_epochs: 150
  lr: 2.8e-4
  useEnergyPrior: False
  adversarial:
    use: False
