run_name: "Good IDD"
modelname: "DoTA"

dotakwgs:
  use_fourier_embedding: True

losskwgs:
  use_high_dose_mask: False

train:
  adversarial:
    use: False
    useRamping: False
    adv_weight: 0.1
    d_update_freq: 5