atlasz:
  num_workers: 8
  batch_size: 16
  prefetch_factor: 2 
  persistent_workers: True
  cache_dir: "/scratch/db/cache"
  dataset_type: "persistent"

komondor:
  num_workers: 0
  batch_size: 32
  prefetch_factor: 0
  data_dir: "/home/nr_dodb/nr_dose_scratch/training"
  dataset_type: "dataset"
  persistent_workers: False