atlasz:
  num_workers: 8
  batch_size: 128
  prefetch_factor: 2 
  persistent_workers: True
  cache_dir: "/scratch/db/cache"
  dataset_type: "persistent"

komondor:
  num_workers: 8
  batch_size: 100
  cache_dir: "/scratch/nr_dose"
  dataset_type: "persistent"
  prefetch_factor: 2
  persistent_workers: True