atlasz:
  num_workers: 4
  batch_size: 128
  cache_dir: "/scratch/db"
  dataset_type: "dataset"

komondor:
  num_workers: 32
  batch_size: 32
  cache_dir: "/home/nr_dodb/nr_dose_scratch"
  dataset_type: "presistent"