
run_name: "Fourier_energy"
modelname: "DoTA"

dotakwgs:
  use_fourier_embedding: True

losskwgs:
  use_high_dose_mask: True
  high_dose_threshold: 0.8
  high_dose_weight: 5.0

train:
  adversarial:
    use: True
