run_name: "Higher_res"
modelname: "DoTA"

dotakwgs:
  in_channels: 2
  out_channels: 1
  channels: [32, 64, 128, 256]
  num_heads: 8
  num_layers: 4
  use_fourier_embedding: True

unetkwgs:
  condition_dim: 3

filmkwgs:
  condition_dim: 3

attentionkwgs:
  condition_dim: 3

losskwgs:
  masked_factor: 10.0
  iid_curve_weight: 0.5
  allMAE_weight: 0.50
  total_variation_weight: 0.01

train:
  num_epochs: 100
  lr: 2.8e-4
  use_warmups: False
  fine_tune: False
  
  adversarial:
    use: True
    adv_weight: 0.1
    d_update_freq: 5
    start_epoch: 50
    ramp_length: 50
    max_mae_weight: 10.0
    def_mae_weight: 10.0
