
run_name: "Fourier_energy"
modelname: "DoTA"

  
dotakwgs:
  use_fourier_embedding: True

losskwgs:
  masked_factor: 10.0
  iid_curve_weight: 0.5
  allMAE_weight: 0.50
  total_variation_weight: 0.01

train:
  adversarial:
    use: True
